SELECT master.*, student_comments.*
FROM
  (SELECT DECODE(QS.ANONYMOUS, 'Y', 'b' ,'N', 'a') SORT_ORDER,
    DECODE(QS.ANONYMOUS, 'Y', CONCAT('ANONYMOUS', SS.STUD_ID),'N', SS.STUD_ID) STUD_ID,
    SS.STUD_ID STUD_ID_ORIG,
    SS.STUD_SURVEY_ID ,
    DECODE(QS.ANONYMOUS, 'Y', CONCAT('ANONYMOUS',CONCAT(COALESCE(S.FNAME,''), CONCAT(' ', CONCAT(COALESCE(S.LNAME,''), CONCAT(' ', COALESCE(S.MI,'')))))), 'N', CONCAT(COALESCE(S.FNAME,''), CONCAT(' ', CONCAT(COALESCE(S.LNAME,''), CONCAT(' ', COALESCE(S.MI,'')))))) STUD_NAME ,
    QS.SURVEY_ID,
    SS.SURVEY_COMPLETION_DATE,
    CS.CPNT_SURVEY_ID,
    CPNT.CPNT_TITLE,
    SQ.SECTION_ID,
    SQ.QUESTION_ID,
    QS.NAME,
    CS.CPNT_TYP_ID,
    CS.CPNT_ID,
    CS.REV_DTE,
    SSEC.SECTION_ORDER,
    SSEC.SECTION_TITLE,
    SSEC.RESOURCE_TYPE,
    SQ.QUESTION_ORDER,
    SQ.QUESTION_TYPE,
    SQ.QUESTION_TEXT,
    SR.STUD_RESPONSE_VALUE,
    CONCAT(COALESCE(INSTDETAIL.FNAME,''), CONCAT(' ', CONCAT(COALESCE(INSTDETAIL.LNAME,''), CONCAT(' ', COALESCE(INSTDETAIL.MI,'')))))  INSTRUCTOR_NAME,
    S.FNAME STUD_FNAME,
    S.LNAME STUD_LNAME,
    S.MI STUD_MI,
    sup.LANME AS manager_lastName,
    sup.FNAME AS manager_firstname,
    S.EMAIL_ADDR,
    S.HIRE_DTE,
    DECODE(SQ.QUESTION_TYPE,'RATING SCALE',
    (SELECT PA_RATING_SCALE_LABEL.RATING_LABEL
    FROM PA_RATING_SCALE_LABEL
    WHERE PA_RATING_SCALE_LABEL.RATING        = SR.STUD_RESPONSE_VALUE
    AND PA_RATING_SCALE_LABEL.RATING_SCALE_ID = SQ.RATING_SCALE_ID
    ), 'OPEN ENDED',MAX(SR.STUD_RESPONSE_TEXT) ,MAX(QAC.CHOICE_LABEL)) ANSWER, 
    
    (SELECT COUNT(*) AS TotalSurveys
    FROM PA_STUD_SURVEY pss,
      PA_CPNT_SURVEY psc
    WHERE psc.CPNT_SURVEY_ID = pss.CPNT_SURVEY_ID
    AND psc.survey_id        = QS.survey_id
    ) TOTAL_SURVEY,
    (SELECT COUNT(*) AS TotalSurveys
    FROM PA_STUD_SURVEY pss,
      PA_CPNT_SURVEY psc
    WHERE psc.CPNT_SURVEY_ID = pss.CPNT_SURVEY_ID
    AND psc.survey_id        = QS.survey_id
    AND pss.survey_status_id = 'COMPLETED'
    ) COMPLETED_SURVEY,
    (SELECT COUNT(*) AS TotalSurveys
    FROM PA_STUD_SURVEY pss,
      PA_CPNT_SURVEY psc
    WHERE psc.CPNT_SURVEY_ID = pss.CPNT_SURVEY_ID
    AND psc.CPNT_SURVEY_ID   = CS.CPNT_SURVEY_ID
    ) TOTAL_ITEM_SURVEY,
    (SELECT COUNT(*) AS TotalSurveys
    FROM PA_STUD_SURVEY pss,
      PA_CPNT_SURVEY psc
    WHERE psc.CPNT_SURVEY_ID = pss.CPNT_SURVEY_ID
    AND psc.CPNT_SURVEY_ID   = CS.CPNT_SURVEY_ID
    AND pss.survey_status_id = 'COMPLETED'
    ) COMPLETED_ITEM_SURVEY,
    SS.SCH_ID SCHDULE_OFFERING,
    SR.STUD_COMMENTS STUDENT_COMMENTS,
    (
    CASE
      WHEN (SELECT COUNT(DISTINCT(RATING_SCALE_ID)) AS V_RATING_SETS
        FROM PA_SURVEY_QUESTION
        WHERE SECTION_ID IN
          ( SELECT SECTION_ID FROM PA_SURVEY_SECTION WHERE SURVEY_ID = QS.SURVEY_ID
          )
        AND QUESTION_TYPE = 'RATING SCALE' ) = 1
      THEN
        (SELECT DECODE(ROUND(SUM(PSR.STUD_RESPONSE_VALUE)/COUNT(*),1),NULL,-1, ROUND(SUM(PSR.STUD_RESPONSE_VALUE)/COUNT(*),1))
        FROM PA_SURVEY_RESPONSES PSR,
          PA_STUD_SURVEY PSS,
          PA_CPNT_SURVEY PCS,
          PA_SURVEY_QUESTION PSQ,
          PA_SSG_INST PSI,
          PA_SSG_LOCN PSL
        WHERE PSS.CPNT_SURVEY_ID     = PCS.CPNT_SURVEY_ID
        AND PSR.STUD_SURVEY_ID       = PSS.STUD_SURVEY_ID
        AND PSR.QUESTION_ID          = PSQ.QUESTION_ID
        AND PSS.SURVEY_STATUS_ID     ='COMPLETED'
        AND PCS.SURVEY_ID            = QS.SURVEY_ID
        AND PSS.CPNT_SURVEY_ID       = CS.CPNT_SURVEY_ID
        AND PSS.STUD_ID              = SS.STUD_ID
        AND PSQ.QUESTION_TYPE        = 'RATING SCALE'
        AND PSR.STUD_RESPONSE_VALUE <> 0
        AND PSS.SCH_ID               = PSI.SCHD_ID(+)
        AND PSS.SCH_ID               = PSL.SCHD_ID(+)
          /**
          and (PCS.CPNT_TYP_ID,PCS.CPNT_ID,PCS.REV_DTE) IN [ItemSearch]
          and PSS.SCH_ID IN [ScheduledOfferingSearch]
          and (PSS.ITEM_COMPLETION_DATE) >= [LearningEventFromDate]
          and NOT (pkg_sql.sub_days(PSS.ITEM_COMPLETION_DATE , 1)) >= [LearningEventToDate]          
          AND PSI.INST_ID IN [InstructorSearch]
          and PSL.LOCN_ID IN [LocationSearch]
          and PCS.IS_ACTIVE = [IncludePreviousItemAssociations]
          */
        )
      ELSE -1
    END ) AS MEAN_SCORE
  FROM PA_QUESTIONNAIRE_SURVEY QS
  LEFT OUTER JOIN PA_CPNT_SURVEY CS
  ON QS.SURVEY_ID = CS.SURVEY_ID
  RIGHT OUTER JOIN PA_STUD_SURVEY SS
  ON CS.CPNT_SURVEY_ID=SS.CPNT_SURVEY_ID
  LEFT OUTER JOIN PA_SURVEY_RESPONSES SR
  ON SS.STUD_SURVEY_ID = SR.STUD_SURVEY_ID
  LEFT OUTER JOIN PA_SURVEY_QUESTION SQ
  ON SR.QUESTION_ID = SQ.QUESTION_ID
  LEFT OUTER JOIN PA_SURVEY_SECTION SSEC
  ON SQ.SECTION_ID = SSEC.SECTION_ID
  LEFT OUTER JOIN PA_QUESTION_ANSWER_CHOICES QAC
  ON QAC.QUESTION_ID = SQ.QUESTION_ID
  LEFT OUTER JOIN PA_SCH_SEG SCHEDSEG 
  ON SCHEDSEG.SCHD_ID = SS.SCH_ID
  LEFT OUTER JOIN PA_SSG_INST INSTRUCTOR 
  ON INSTRUCTOR.SCHD_ID = SCHEDSEG.SCHD_ID AND INSTRUCTOR.SSG_SEG_NUM = SCHEDSEG.SSG_SEG_NUM
  LEFT OUTER JOIN PA_SSG_LOCN LOCATION1
  ON LOCATION1.SCHD_ID = SS.SCH_ID
  LEFT OUTER JOIN PA_INST INSTDETAIL 
  ON INSTDETAIL.INST_ID = SR.INST_ID,
    PA_STUDENT S,
    PA_STUDENT sup,
     PV_COURSE CPNT
  WHERE ( QAC.ANSWER_ID      = SR.STUD_RESPONSE_VALUE
  OR SR.STUD_RESPONSE_VALUE IS NULL
  OR SQ.QUESTION_TYPE        = 'RATING SCALE' )
  AND SQ.SECTION_ID         IS NOT NULL
  AND SS.survey_status_id    = 'COMPLETED'
  AND ( SS.STUD_ID           = NULL
  OR SS.STUD_ID              = S.STUD_ID )
  AND s.super = sup.stud_id
  AND CS.CPNT_TYP_ID         = CPNT.CPNT_TYP_ID
  AND CS.CPNT_ID             = CPNT.CPNT_ID
  AND CS.REV_DTE             = CPNT.REV_DTE
  AND QS.LEVEL_INDICATOR     = 1
    /**
    and QS.SURVEY_ID in [SurveyIDSearch]
    and SS.STUD_ID in [UserSearch]
    and (SS.ITEM_COMPLETION_DATE) >= [LearningEventFromDate]
    and NOT (pkg_sql.sub_days(SS.ITEM_COMPLETION_DATE , 1)) >= [LearningEventToDate]
    and SS.SCH_ID in [ScheduledOfferingSearch]    
    and INSTRUCTOR.INST_ID IN [InstructorSearch]
    AND LOCATION1.LOCN_ID in [LocationSearch]
    and QS.IS_ACTIVE  = [QuestionnaireSurveyStatus]
    and CS.IS_ACTIVE  = [IncludePreviousItemAssociations]
    and (CS.cpnt_typ_id,CS.cpnt_id,CS.rev_dte) in [ItemSearch]
    and [security:PA_QUESTIONNAIRE_SURVEY QS]
    */
  GROUP BY DECODE(QS.ANONYMOUS, 'Y', 'b' ,'N', 'a'),
    DECODE(QS.ANONYMOUS, 'Y', CONCAT('ANONYMOUS', SS.STUD_ID),'N', SS.STUD_ID),
    S.FNAME,
    S.LNAME,
    S.MI,
    S.EMAIL_ADDR,
    S.HIRE_DTE,
    sup.LNAME AS manager_lastname,
    sup.FNAME AS manager_firstname,
    SS.STUD_ID,
    SS.STUD_SURVEY_ID,
    DECODE(QS.ANONYMOUS, 'Y', CONCAT('ANONYMOUS',CONCAT(COALESCE(S.FNAME,''), CONCAT(' ', CONCAT(COALESCE(S.LNAME,''), CONCAT(' ', COALESCE(S.MI,'')))))), 'N', CONCAT(COALESCE(S.FNAME,''), CONCAT(' ', CONCAT(COALESCE(S.LNAME,''), CONCAT(' ', COALESCE(S.MI,'')))))) ,
    
    QS.SURVEY_ID,
    SS.SURVEY_COMPLETION_DATE,
    CS.CPNT_SURVEY_ID,
    CPNT.CPNT_TITLE,
    SQ.SECTION_ID,
    SQ.QUESTION_ID,
    QS.NAME,
    CS.CPNT_TYP_ID,
    CS.CPNT_ID,
    CS.REV_DTE,
    SSEC.SECTION_ORDER,
    SSEC.SECTION_TITLE,
    SSEC.RESOURCE_TYPE,
    SQ.QUESTION_ORDER,
    SQ.QUESTION_TYPE,
    SQ.QUESTION_TEXT,
    SR.STUD_RESPONSE_TEXT,
    SR.STUD_RESPONSE_VALUE,
    SQ.RATING_SCALE_ID,
    SS.SCH_ID,
    SR.STUD_COMMENTS,
    INSTDETAIL.FNAME,
    INSTDETAIL.LNAME,
    INSTDETAIL.MI,
    S.FNAME,
    S.LNAME,
    S.MI,
    S.EMAIL_ADDR,
    sup.LNAME AS manager_lastname,
    sup.FNAME AS manager_firstname,
    S.HIRE_DTE
    ORDER BY STUD_ID,
 		CS.CPNT_SURVEY_ID,
  		SQ.QUESTION_ORDER
  ) master,
  (SELECT DISTINCT SR1.stud_comments ,
    ss.cpnt_survey_id,
    sr1.question_id,
    ss.stud_id
  FROM PA_SURVEY_RESPONSES SR1,
    PA_STUD_SURVEY SS
  WHERE SR1.stud_survey_id = SS.stud_survey_id
  AND SR1.stud_comments  IS NOT NULL
   ) student_comments
WHERE student_comments.cpnt_survey_id(+)=master.cpnt_survey_id
AND student_comments.question_id(+)     =master.question_id
AND student_comments.stud_id(+)         =master.stud_id
/** and master.STUD_ID in [UserSearch] */
